### PR TITLE
validation: add type check in equals() for numeric comparison

### LINKED ISSUE #241: Surprising comparison when using stringified integer duplicated
Hello

We have an issue on Helm (https://github.com/helm/helm/issues/31570) that is related to how jsonschema parses the schema when we have a stringified integer that is duplicated with an integer.

The behavior can be surprising, especially when it is order dependent. We can imagine the surprise on long and complex enums.

For example:
- enum: ["1", 1] fails with "items at 0 and 1 are equal"
- enum: [1, "1"] succeeds

The root cause is in the `equals()` function in `util.go`. It uses `fmt.Sprint()` to serialize values before numeric comparison with `big.Rat`, which makes string "1" and number 1 compare as equal. If I'm correct.

This test program demonstrates both cases.

```go
package main

import (
	"fmt"
	"strings"

	"github.com/santhosh-tekuri/jsonschema/v6"
)

func testSchema(schemaJSON string, description string) {
	fmt.Println(description)

	compiler := jsonschema.NewCompiler()
	doc, err := jsonschema.UnmarshalJSON(strings.NewReader(schemaJSON))
	if err != nil {
		fmt.Printf("Error: %v\n", err)
		return
	}
	if err := compiler.AddResource("schema.json", doc); err != nil {
		fmt.Printf("Error: %v\n", err)
		return
	}

	_, err = compiler.Compile("schema.json")
	if err != nil {
		fmt.Printf("\nNot good %v\n\n", err)
		return
	}

	fmt.Println("\nGood ! \n")
}

func main() {
	schemaJSON1 := `{
		"$schema": "http://json-schema.org/draft-07/schema#",
		"type": "object",
		"properties": {
			"value": {
				"enum": ["1", 1]
			}
		}
	}`
	testSchema(schemaJSON1, "Test 1: enum: [\"1\", 1] (string first)")

	schemaJSON2 := `{
		"$schema": "http://json-schema.org/draft-07/schema#",
		"type": "object",
		"properties": {
			"value": {
				"enum": [1, "1"]
			}
		}
	}`
	testSchema(schemaJSON2, "Test 2: enum: [1, \"1\"] (number first)")
}
```

### PR DESCRIPTION
**Pull request by benoittgt**
Previously, equals() compared string "1" and json.Number("1") as equal because both were converted to strings via fmt.Sprint() and parsed as numbers, ignoring type differences.

Now, numeric comparison only occurs when both values are numeric types, preserving JSON type distinction in enum duplicate detection.

Previous errors:
- enum: ["1", 1] fails with "items at 0 and 1 are equal"
- enum: [1, "1"] succeeds

Schema example:
```json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "properties": {
    "autoscaling": {
      "description": "autoscaling properties",
      "properties": {
        "minReplicas": {
            "enum": ["1", 1]
        }
      },
      "type": "object"
    }
  },
  "title": "Values",
  "type": "object"
}
```

Closes: #241

### CODE REVIEW

File: util.go [hunk 1]
```diff
@@ -320,9 +320,15 @@ func equals(v1, v2 any) (bool, ErrorKind) {
 		v2, ok := v2.(string)
 		return ok && v1 == v2, nil
 	case json.Number, float32, float64, int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64:
-		num1, ok1 := new(big.Rat).SetString(fmt.Sprint(v1))
-		num2, ok2 := new(big.Rat).SetString(fmt.Sprint(v2))
-		return ok1 && ok2 && num1.Cmp(num2) == 0, nil
+		switch v2.(type) {
```
Comment (santhosh-tekuri) [inline util.go]: can you replace switch with `if typeOf(v2)~=numberType { return false }`

Comment (benoittgt) [reply util.go]: Thanks. Done via https://github.com/santhosh-tekuri/jsonschema/pull/242/commits/2ef0323aefe8100bf81f309e1412782662cd9cb1

**Comment by benoittgt** [comment]
@santhosh-tekuri 

Thanks for the merge. Do you know when the next release is expected?
