### PR TITLE
validator: check invalid floats NaN/Inf

### LINKED ISSUE #248: Validate panics on NaN/Inf float64 when schema has numeric constraints
Passing `math.NaN()`, `math.Inf(1)`, or `math.Inf(-1)` to `Schema.Validate()` causes a nil pointer dereference when the schema contains any numeric constraint (`minimum`, `maximum`, `exclusiveMinimum`, `exclusiveMaximum`, or `multipleOf`).

### Reproduction

```go
package main

import (
	"math"
	"strings"

	"github.com/santhosh-tekuri/jsonschema/v6"
)

func main() {
	c := jsonschema.NewCompiler()
	doc, _ := jsonschema.UnmarshalJSON(strings.NewReader(`{"minimum": 0}`))
	_ = c.AddResource("test.json", doc)
	sch, _ := c.Compile("test.json")
	sch.Validate(math.NaN()) // panic: runtime error: invalid memory address or nil pointer dereference
}
```

All 15 combinations of {NaN, +Inf, -Inf} x {minimum, maximum, exclusiveMinimum, exclusiveMaximum, multipleOf} panic.

For comparison, `sch.Validate(42.5)` validates correctly and `sch.Validate("not a number")` returns a type error as expected.

### Root Cause

`numValidate()` at validator.go:517-522 builds a `*big.Rat` via `SetString(fmt.Sprintf("%v", v))`. For NaN/Inf strings, `SetString` returns `(nil, false)`, but the `ok` return is discarded with `_`. `numVal` stays nil, and the subsequent `num().Cmp(...)` calls dereference nil.

Contributing factor: `typeOf()` in schema.go returns `numberType` for all `float64` values including NaN/Inf, so they pass the type check and reach `numValidate()` unchecked.

### Impact

Only affects direct API callers passing computed float64 values -- standard `encoding/json` never produces NaN/Inf. NaN and Inf are not valid JSON values per RFC 8259, so the validator should reject them with a validation error rather than panicking.

I have a fix ready and will open a PR shortly.

### PR DESCRIPTION
**Pull request by vnykmshr**
Fixes #248.

`typeOf()` now returns `invalidType` for NaN/Inf `float64` and `float32` values, so they hit the existing `InvalidJsonValue` error path at validator.go:92-94 instead of reaching `numValidate()` where `big.Rat.SetString` returns nil.

### What changed

- `schema.go`: split the `float64` and `float32` cases out of the numeric type switch in `typeOf()`, adding `math.IsNaN`/`math.IsInf` guards that return `invalidType`
- `nan_inf_test.go`: test that all three values (NaN, +Inf, -Inf) produce a validation error instead of a panic

### Alternative considered

A guard at the top of `numValidate()` would also work, but catching it in `typeOf()` prevents these values from reaching any validation logic at all.

### CODE REVIEW

File: nan_inf_test.go [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+
+import (
+	"math"
+	"strings"
+	"testing"
+
+	"github.com/santhosh-tekuri/jsonschema/v6"
+)
+
+func TestNaNInfPanic(t *testing.T) {
```
Comment (santhosh-tekuri) [inline nan_inf_test.go]: change function name to `TestInvalidFloats`

File: nan_inf_test.go [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+	c := jsonschema.NewCompiler()
+	doc, err := jsonschema.UnmarshalJSON(strings.NewReader(`{"minimum": 0}`))
+	if err != nil {
+		t.Fatal(err)
+	}
+	if err := c.AddResource("test.json", doc); err != nil {
```
Comment (santhosh-tekuri) [inline nan_inf_test.go]: use `schema.json` instead of `test.json`

File: validator_test.go [hunk 3]
```diff
@@ -0,0 +1,32 @@
+package jsonschema_test
```
Comment (santhosh-tekuri) [inline validator_test.go:1]: change filename to `validator_test.go`
change commit msg: `validator: check invalid floats NaN/Inf`
